"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c5e=0nl+#7q1#cufm0%$#*em=4j@m5m6v&qg-84$&$bgny+c*2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

# config/settings.py

INSTALLED_APPS = [
    'django.contrib.admin', # admin interface
    'django.contrib.auth', # Para autenticação de usuários
    'django.contrib.contenttypes', # Para gerenciar tipos de conteúdo
    'django.contrib.sessions', # Para gerenciar sessões de usuários
    'django.contrib.messages', # Para mensagens de feedback ao usuário
    'django.contrib.staticfiles', # Para arquivos estáticos como CSS e JS
    'rest_framework', # Django REST Framework para construir APIs
    # Apps de terceiros
    'django_filters',  # Para filtros avançados na API
    'corsheaders',  # Para permitir CORS
    'localidades.apps.LocalidadesConfig', # Nosso app de localidades
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.security.SecurityMiddleware', # Segurança básica
    'django.contrib.sessions.middleware.SessionMiddleware', # Middleware para gerenciar sessões
    'django.middleware.common.CommonMiddleware', # Middleware comum para funcionalidades básicas
    'django.middleware.csrf.CsrfViewMiddleware', # Proteção contra CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Middleware para autenticação de usuários
    'django.contrib.messages.middleware.MessageMiddleware', # Middleware para mensagens de feedback
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Proteção contra clickjacking
]

ROOT_URLCONF = 'config.urls' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
# Permite que o frontend acesse a API Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Endereço do nosso frontend React
    "http://localhost:3001", # Porta alternativa do React
    "https://3000-i4oregv2txxi68p046id1-33f0fcd4.manusvm.computer", # Domínio exposto do frontend
]

# Para desenvolvimento, permite todos os origins
CORS_ALLOW_ALL_ORIGINS = True
