# Generated by Django 5.2.4 on 2025-07-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalhaRio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Calha de Rio',
                'verbose_name_plural': 'Calhas de Rios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Código IBGE')),
                ('uf', models.CharField(default='AM', max_length=2, verbose_name='UF')),
                ('municipio', models.CharField(db_index=True, max_length=100, verbose_name='Município')),
                ('nome_comunidade', models.CharField(db_index=True, max_length=255, verbose_name='Nome da Comunidade')),
                ('tipo_comunidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Comunidade')),
                ('domicilios', models.IntegerField(blank=True, null=True, verbose_name='Domicílios/UCs')),
                ('total_ligacoes', models.IntegerField(blank=True, null=True, verbose_name='Total de Ligações')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('fonte_dados', models.CharField(choices=[('3ª Tranche', 'Tranche'), ('Convencional', 'Convencional')], max_length=20, verbose_name='Fonte dos Dados')),
                ('calha_rio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades', to='localidades.calhario', verbose_name='Calha de Rio')),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'unique_together': {('nome_comunidade', 'municipio', 'fonte_dados')},
            },
        ),
    ]
