# Generated by Django 5.2.4 on 2025-07-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do Município (IBGE)')),
                ('uf', models.CharField(max_length=5, verbose_name='UF')),
                ('municipio', models.CharField(max_length=255, verbose_name='Nome do Município')),
                ('comunidade', models.CharField(max_length=255, verbose_name='Nome da Comunidade')),
                ('tipo_comunidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Comunidade')),
                ('domicilios', models.IntegerField(blank=True, null=True, verbose_name='Domicílios')),
                ('total_ligacoes', models.IntegerField(blank=True, null=True, verbose_name='Total de Ligações')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'unique_together': {('comunidade', 'municipio')},
            },
        ),
    ]
